services:
  radicle-node:
    image: docker.io/khuedoan/radicle-server
    command: "radicle-node"
    user: "1000:100"
    userns_mode: keep-id
    environment:
      - RAD_HOME=/radicle
    ports:
      - 8776:8776
    volumes:
      - .radicle:/radicle
  radicle-httpd:
    image: docker.io/khuedoan/radicle-server
    command: "radicle-httpd"
    user: "1000:100"
    userns_mode: keep-id
    environment:
      - RAD_HOME=/radicle
    ports:
      - 8080:8080
    volumes:
      - .radicle:/radicle
  temporal:
    image: docker.io/temporalio/server
    entrypoint:
      - temporal
      - server
      - start-dev
      - --ip=0.0.0.0
    ports:
      - 7233:7233
      - 8233:8233
  registry:
    image: registry
    ports:
      - 5000:5000
    environment:
      REGISTRY_LOG_LEVEL: error
  fake-argo:
    image: docker.io/stefanprodan/podinfo
    ports:
      - 9898:9898
