services:
  micropaas:
    build: .
    ports:
      - 2222:2222
    environment:
      SOFT_SERVE_INITIAL_ADMIN_KEYS: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIN5ue4np7cF34f6dwqH1262fPjkowHQ8irfjVC156PCG'
      REGISTRY_HOST: 'localhost:5000'
      GITOPS_REPO: 'gitops'
      LOG_LEVEL: 'debug'
    volumes:
      - micropaas-db:/var/lib/micropaas/db
      - micropaas-ssh:/var/lib/micropaas/ssh
      - micropaas-web:/var/lib/micropaas/web
      - cache:/var/cache
      - /var/run/docker.sock:/var/run/docker.sock
    develop:
      watch:
        - action: rebuild
          path: Cargo.toml
        - action: rebuild
          path: src
  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - micropaas-web:/usr/share/nginx/html
  registry:
    image: registry
    ports:
      - 5000:5000
    environment:
      REGISTRY_LOG_LEVEL: error

volumes:
  cache: {}
  nix: {}
  micropaas-db: {}
  micropaas-ssh: {}
  micropaas-web: {}
