services:
  micropaas:
    build: .
    ports:
      - 2222:2222
    environment:
      SOFT_SERVE_INITIAL_ADMIN_KEYS: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIN5ue4np7cF34f6dwqH1262fPjkowHQ8irfjVC156PCG'
    volumes:
      - micropaas-ssh:/var/lib/micropaas/ssh
      - micropaas-web:/var/lib/micropaas/web
      # Only for development
      - ./hooks:/var/lib/micropaas/hooks
      - ./stagit:/etc/stagit
  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - micropaas-web:/usr/share/nginx/html

volumes:
  nix: {}
  micropaas-ssh: {}
  micropaas-web: {}
