#!/bin/sh

set -eu

name=$(basename "$(pwd)")

reposdir="${SOFT_SERVE_DATA_PATH}/repos"
dir="${reposdir}/${name}"
htmldir="${SOFT_SERVE_DATA_PATH}/web"
stagitdir="/"
destdir="${htmldir}${stagitdir}"

r=$(basename "${name}")
d=$(basename "${name}" ".git")

mkdir -p "${destdir}/${d}"
cd "${destdir}/${d}" || exit 1

stagit "${reposdir}/${r}"
cp /etc/stagit/* .

stagit-index "${reposdir}/"*/ > "${destdir}/index.html"
cp /etc/stagit/* "${destdir}"
