#!/usr/bin/env bash

# TODO rewrite?

set -eu

REF_NAME="${1}"
OLD_OBJECT="${2}"
NEW_OBJECT="${3}"
DEFAULT_BRANCH="${DEFAULT_BRANCH:-master}"

WORKDIR="$(mktemp -d)"
CACHE_DIR="/var/cache/micropaas/${SOFT_SERVE_REPO_NAME}/${REF_NAME}"

git worktree add --quiet "${WORKDIR}" "${NEW_OBJECT}"

pushd "${WORKDIR}"

if [ -f flake.nix ] && [ -f Makefile ] && grep --quiet --regexp "^ci:$" Makefile; then
    mkdir -p "${CACHE_DIR}"
    nix develop --quiet --command \
        make ci REF_NAME="${REF_NAME}" OLD_OBJECT="${OLD_OBJECT}" NEW_OBJECT="${NEW_OBJECT}" CACHE_DIR="${CACHE_DIR}"
fi

if [ -f "Dockerfile" ]; then
    docker build . --tag "${SOFT_SERVE_REPO_NAME}:${NEW_OBJECT}"

    if [ "${REF_NAME}" = "refs/heads/${DEFAULT_BRANCH}" ]; then
        REGISTRY_HOST="${REGISTRY_HOST:-docker.io}"
        IMAGE_TAG="${REGISTRY_HOST}/${SOFT_SERVE_REPO_NAME}:${NEW_OBJECT}"

        docker tag "${SOFT_SERVE_REPO_NAME}:${NEW_OBJECT}" "${IMAGE_TAG}"
        # TODO docker login
        docker push --quiet "${IMAGE_TAG}"

        GITOPS_REPO="${GITOPS_REPO:-gitops}"

        pushd "/var/lib/micropaas/repos/${GITOPS_REPO}.git"
        [ -d "${DEFAULT_BRANCH}" ] && git worktree remove --force "${DEFAULT_BRANCH}"
        git worktree add --quiet "${DEFAULT_BRANCH}" "${DEFAULT_BRANCH}"
        pushd "${DEFAULT_BRANCH}"
        # GIT_DIR is '.' by default, which will not work when cd to another repo worktree
        unset GIT_DIR
        yq eval ".app-template.controllers.main.containers.main.image.tag = \"${NEW_OBJECT}\"" -i "apps/${SOFT_SERVE_REPO_NAME}/values.yaml"
        git add .
        git \
            -c user.name="Khue Doan" \
            -c user.email="mail@khuedoan.com" \
            commit \
            --message "chore(${SOFT_SERVE_REPO_NAME}): update image tag to ${NEW_OBJECT}"

        # Trigger ArgoCD sync with webhook for faster sync
        # TODO https://github.com/argoproj/argo-cd/issues/12268
        # Pretending to be GitHub for now, read this code to understand the required payload
        # https://github.com/argoproj/argo-cd/blob/master/util/webhook/webhook.go
        json_payload=$(cat <<EOF
{
  "ref": "refs/heads/master",
  "before": "0000000000000000000000000000000000000000",
  "after": "0000000000000000000000000000000000000000",
  "commits": [
    {
      "added": [],
      "modified": [],
      "modified": []
    }
  ],
  "repository": {
    "html_url": "http://micropaas.micropaas.svc.cluster.local:8080/gitops",
    "default_branch": "master"
  }
}
EOF
        )
        wget \
            --quiet \
            --output-document - \
            --header='Content-Type:application/json' \
            --header='X-GitHub-Event:push' \
            --post-data "$json_payload" \
            http://argocd-server.argocd.svc.cluster.local/api/webhook

        popd
        git worktree remove "${DEFAULT_BRANCH}"
        popd
    fi
fi

popd

git worktree remove "$WORKDIR"
