#!/bin/sh

# TODO rewrite?

set -eu

REF_NAME="${1}"
OLD_OBJECT="${2}"
NEW_OBJECT="${3}"

WORKDIR="$(mktemp -d)"
CACHE_DIR="/var/cache/micropaas/${SOFT_SERVE_REPO_NAME}/${REF_NAME}"

git worktree add --quiet "${WORKDIR}" "${NEW_OBJECT}"

pushd "${WORKDIR}"

if [ -f flake.nix ] && [ -f Makefile ] && grep --quiet --regexp "^ci:$" Makefile; then
    mkdir -p "${CACHE_DIR}"
    nix develop --command \
        make ci REF_NAME="${REF_NAME}" OLD_OBJECT="${OLD_OBJECT}" NEW_OBJECT="${NEW_OBJECT}" CACHE_DIR="${CACHE_DIR}"
fi

if [ -f "Dockerfile" ]; then
    docker build .
fi

popd

git worktree remove "$WORKDIR"
